export const subjectData = [
      //Sem 1 complete
      "CLP (Classical Physics)",
      "M1 (Mathematics-I)",
      "BE (Basic Electronics)",
      "CP (Computer Programming )",
      "TCE (Technical Communication in English)",

      //Sem 2 complete
      "M2 (Mathematics-II)",
      "DSA (Data Structures and Algorithms)",
      "EEB (Environmental Ecology & Biology)",
      "VEE (Value Education and Ethics)",
      "ANEL (Analog Electronics)",
      "DMS (Discrete Mathematical Structures)",
      "IMP (Introduction to Modern Physics)",
      "DSY (Digital Systems)",
      "NAS (Network Analysis and Synthesis)",
      "EPM (Engineering Physical Metallurgy)",

      //Sem 3
      "M3 (Mathematics-III)",
      "COA (Computer Organization and Architecture)",
      "AP (Advanced Programming)",
      "SNS (Signals and Systems)",
      "IDBMS (Information and Database Management Systems)",
      "EFE (Economics for Engineers)",
      "PTS (Psychology, Technology and Society)",
      "OTA (Optimization Techniques and Applications)",
      "SEMI (Semiconductor Devices and Circuits)",
      "EEM (Engineering Electromagnetics)",
      "DCS (Digital Circuits and Systems)",
      "(Modern Electrical and Electronics Technologies)",
      "(Mechanics of Solids)",
      "(Manufacturing Technology-1)",
      "(Engineering Thermodynamics)",
      "(Industrial Engineering and Management)",

      //Sem 4
      "DAA (Design and Analysis of Algorithms)",
      "OS (Operating Systems)",
      "CSE (Control System Engineering)",
      "POC (Principles of Communication)",
      "PNS (Probability and Statistics)",
      "TOC (Theory of Computation)",
      "CN (Computer Networks)",
      "DPIoT (Device Programming for IoT)",
      "DIP (Digital Image Processing)",
      "CT (Coding Theory)",
      "MWE (Microwave Engineering)",
      "IVLSI (Introduction to VLSI)",
      "(Machine Design–1)",
      "(Kinematics & Dynamics)",
      "(Fluid Mechanics & Machinery)",
      "(Metrology, Instrumentation and control)",
      "(Total Quality Management)",
      "(Manufacturing Technology–2)",
];
